export const IPC_SHOW_WINDOW = 'IPC_SHOW_WINDOW'
export const IPC_LOGOUT = 'IPC_LOGOUT'
export const IPC_GET_FB_TOKEN_REQ = 'IPC_GET_FB_TOKEN_REQ'
export const IPC_GET_FB_TOKEN_RES = 'IPC_GET_FB_TOKEN_RES'
