export const FB_GET_TOKEN_REQUEST		= 'FB_GET_TOKEN_REQUEST';
export const FB_GET_TOKEN_SUCCESS		= 'FB_GET_TOKEN_SUCCESS';
export const FB_GET_TOKEN_FAILURE		= 'FB_GET_TOKEN_FAILURE';

export const FB_GET_ID_REQUEST			= 'FB_GET_ID_REQUEST';
export const FB_GET_ID_SUCCESS			= 'FB_GET_ID_SUCCESS';
export const FB_GET_ID_FAILURE			= 'FB_GET_ID_FAILURE';

export const TINDER_API					= 'TINDER_API';
export const API_AUTHORIZE				= 'API_AUTHORIZE';
export const API_AUTHORIZE_SUCCESS		= 'API_AUTHORIZE_SUCCESS';
export const API_REQUIRE_AUTHORIZATION	= 'API_REQUIRE_AUTHORIZATION';
export const API_SET_TOKEN				= 'API_SET_TOKEN';
export const API_SET_TOKEN_SUCCESS		= 'API_SET_TOKEN_SUCCESS';
export const API_GET_HISTORY			= 'API_GET_HISTORY';
export const API_GET_HISTORY_SUCCESS	= 'API_GET_HISTORY_SUCCESS';
export const API_GET_UPDATES			= 'API_GET_UPDATES';
export const API_GET_UPDATES_SUCCESS	= 'API_GET_UPDATES_SUCCESS';
export const API_GET_USER				= 'API_GET_USER';
export const API_GET_USER_SUCCESS		= 'API_GET_USER_SUCCESS';
export const API_GET_PROFILE			= 'API_GET_PROFILE';
export const API_GET_PROFILE_SUCCESS	= 'API_GET_PROFILE_SUCCESS';
export const API_GET_REC				= 'API_GET_REC';
export const API_GET_REC_SUCCESS		= 'API_GET_REC_SUCCESS';

export const SHOW_NOTIFICATION          = 'SHOW_NOTIFICATION';

export const LF_FB_TOKEN            	= 'LF_FB_TOKEN';
export const LF_FB_ID               	= 'LF_FB_ID';
export const LF_FB_TOKEN_EXPIRES_AT 	= 'LF_FB_TOKEN_EXPIRES_AT';
export const LF_TINDER_TOKEN        	= 'LF_TINDER_TOKEN';
export const LF_CURRENT_VIEW        	= 'LF_CURRENT_VIEW';
export const LF_TINDER_MATCHES      	= 'LF_TINDER_MATCHES';
export const LF_TINDER_PROFILE			= 'LF_TINDER_PROFILE';

export const VIEW_MAIN					= 'VIEW_MAIN';
export const VIEW_AUTH					= 'VIEW_AUTH';
export const VIEW_LOADING				= 'VIEW_LOADING';

export const WORKER_SET_MATCHES         = 'WORKER_SET_MATCHES';
export const WORKER_GET_MATCHES         = 'WORKER_GET_MATCHES';
export const WORKER_SET_PROFILE         = 'WORKER_SET_PROFILE';
export const WORKER_SET_PERSON          = 'WORKER_SET_PERSON';
export const WORKER_GET_INITIAL         = 'WORKER_GET_INITIAL';
export const WORKER_SET_UPDATES         = 'WORKER_SET_UPDATES';