// @flow
export const GRAPHQL = 'GRAPHQL'
export const GRAPHQL_SUBSCRIPTIONS = 'GRAPHQL_SUBSCRIPTIONS' //TODO: implement proper subscriptions

export const SUBSCRIPTION_MATCHES_ALL = 'SUBSCRIPTION_MATCHES_ALL';
export const SUBSCRIPTION_MATCH = 'SUBSCRIPTION_MATCH';