// @flow
export {normalizeMatch} from './normalizeMatch'
export {normalizeMessage} from './normalizeMessage'
export {normalizePerson} from './normalizePerson'
export {success} from './statuses'
export {emojify} from './emojify'
export {handleUpdatesFactory} from './handleUpdatesFactory'
export {count} from './count'
export {insert} from './insert'
export {getUpdatesFactory} from './getUpdatesFactory'
export {isOnline} from './isOnline'